# Generated by Django 4.1.7 on 2023-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='headline',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
